config/routes.rb
Rails.application.routes.draw do
  resources :beneficiaries
  resources :training_attendeds
  resources :honors_and_awards
  resources :professional_memberships
  resources :working_experiences
  resources :qualification_details
  resources :bank_accounts
  resources :payrolls
  resources :relatives
  resources :children
  resources :legal_spouses
  devise_for :users
  root 'pages#login'
  resources :personal_details
  resources :pins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'pins' => 'pins#index'
#personal_detail - spouse - children - relatives - qualification - experience - honor - training
  #registration routes
  get 'staff_register' => 'personal_details#new'
  get 'staff_register2' => 'legal_spouses#new'
  get 'staff_register3' => 'children#new'
  get 'staff_register4' => 'relatives#new'
  get 'staff_register5' => 'payrolls#new'
  get 'staff_register6' => 'bank_accounts#new'
  get 'staff_register7' => 'qualification_details#new'
  get 'staff_register8' => 'working_experiences#new'
  get 'staff_register9' => 'professional_memberships#new'
  get 'staff_register10' => 'honors_and_awards#new'
  get 'staff_register11' => 'training_attendeds#new'
  get 'staff_register_finish' => 'pages#finish_register_staff'

  get 'admin_home' => 'pages#admin_home'
  get 'view_all_staff' => 'pages#staff_management'
  get 'show_staff_table' => 'personal_details#index'
  get 'show_training_table' => 'training_attendeds#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bank_account.rb
class BankAccount < ApplicationRecord
  belongs_to :personal_detail
end

app/models/beneficiary.rb
class Beneficiary < ApplicationRecord
end

app/models/child.rb
class Child < ApplicationRecord
  belongs_to :personal_detail
end

app/models/honors_and_award.rb
class HonorsAndAward < ApplicationRecord
  belongs_to :personal_detail
end

app/models/legal_spouse.rb
class LegalSpouse < ApplicationRecord
  belongs_to :personal_detail
end

app/models/payroll.rb
class Payroll < ApplicationRecord
  belongs_to :personal_detail
end

app/models/personal_detail.rb
class PersonalDetail < ApplicationRecord

  has_one_attached :staff_image
  has_one :legal_spouse
end

app/models/pin.rb
class Pin < ApplicationRecord
end

app/models/qualification_detail.rb
class QualificationDetail < ApplicationRecord
  belongs_to :personal_detail
end

app/models/relative.rb
class Relative < ApplicationRecord
  belongs_to :personal_detail
end

app/models/training_attended.rb
class TrainingAttended < ApplicationRecord
  belongs_to :personal_detail
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/working_experience.rb
class WorkingExperience < ApplicationRecord
  belongs_to :personal_detail
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def login
  end

  def admin_home
  end

  def staff_management
    @personal_details = PersonalDetail.all
  end

  def finish_register_staff
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = Pin.new
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = Pin.new(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:text1, :text2)
    end
end

app/controllers/relatives_controller.rb
class RelativesController < ApplicationController
  before_action :set_relative, only: [:show, :edit, :update, :destroy]

  # GET /relatives
  # GET /relatives.json
  def index
    @relatives = Relative.all
  end

  # GET /relatives/1
  # GET /relatives/1.json
  def show
  end

  # GET /relatives/new
  def new
    @relative = Relative.new
    @current_user_register = session[:register_session]
  end

  # GET /relatives/1/edit
  def edit
  end

  # POST /relatives
  # POST /relatives.json
  def create
    @relative = Relative.new(relative_params)

    respond_to do |format|
      if @relative.save
        format.html { redirect_to staff_register5_path, notice: 'Relative was added.' }
        format.json { render :show, status: :created, location: @relative }
      else
        format.html { render :new }
        format.json { render json: @relative.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /relatives/1
  # PATCH/PUT /relatives/1.json
  def update
    respond_to do |format|
      if @relative.update(relative_params)
        format.html { redirect_to @relative, notice: 'Relative was successfully updated.' }
        format.json { render :show, status: :ok, location: @relative }
      else
        format.html { render :edit }
        format.json { render json: @relative.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /relatives/1
  # DELETE /relatives/1.json
  def destroy
    @relative.destroy
    respond_to do |format|
      format.html { redirect_to relatives_url, notice: 'Relative was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_relative
      @relative = Relative.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def relative_params
      params.require(:relative).permit(:relative_name, :relative_nric, :relative_relationship, :relative_tel_no, :relative_hp_no, :relative_perm_address, :relative_postcode, :personal_detail_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payrolls_helper.rb
module PayrollsHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/relatives_helper.rb
module RelativesHelper
end

app/views/relatives/_form.html.erb
<%= form_with(model: relative, local: true) do |form| %>
  <% if relative.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(relative.errors.count, "error") %> prohibited this relative from being saved:</h2>

      <ul>
      <% relative.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :relative_name %>
    <%= form.text_field :relative_name %>
  </div>

  <div class="field">
    <%= form.label :relative_nric %>
    <%= form.number_field :relative_nric %>
  </div>

  <div class="field">
    <%= form.label :relative_relationship %>
    <%= form.text_field :relative_relationship %>
  </div>

  <div class="field">
    <%= form.label :relative_tel_no %>
    <%= form.text_field :relative_tel_no %>
  </div>

  <div class="field">
    <%= form.label :relative_hp_no %>
    <%= form.text_field :relative_hp_no %>
  </div>
  <div class="field">
    <%= form.label :relative_perm_address %>
    <%= form.text_area :relative_perm_address %>
  </div>
  <div class="field">
    <%= form.label :relative_postcode %>
    <%= form.number_field :relative_postcode %>
  </div>

  <div class="field">
    <%= form.label :personal_detail_id %>
    <%= form.text_field :personal_detail_id, value: "#{@current_user_register}" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/relatives/edit.html.erb
<h1>Editing Relative</h1>

<%= render 'form', relative: @relative %>

<%= link_to 'Show', @relative %> |
<%= link_to 'Back', relatives_path %>

app/views/relatives/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Relatives</h1>

<table>
  <thead>
    <tr>
      <th>Relative name</th>
      <th>Relative nric</th>
      <th>Relative relationship</th>
      <th>Relative tel no</th>
      <th>Relative hp no</th>
      <th>Relative perm address</th>
      <th>Relative postcode</th>
      <th>Personal detail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @relatives.each do |relative| %>
      <tr>
        <td><%= relative.relative_name %></td>
        <td><%= relative.relative_nric %></td>
        <td><%= relative.relative_relationship %></td>
        <td><%= relative.relative_tel_no %></td>
        <td><%= relative.relative_hp_no %></td>
        <td><%= relative.relative_perm_address %></td>
        <td><%= relative.relative_postcode %></td>
        <td><%= relative.personal_detail %></td>
        <td><%= link_to 'Show', relative %></td>
        <td><%= link_to 'Edit', edit_relative_path(relative) %></td>
        <td><%= link_to 'Destroy', relative, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Relative', new_relative_path %>

app/views/relatives/new.html.erb
<%= render "layouts/menubar"%>
<div class="container">
  <ul class="breadcrumb">
    <li class="breadcrumb-item"><a href="#">Personal Detail</a></li>
    <li class="breadcrumb-item"><a href="#">Legal Spouse</a></li>
    <li class="breadcrumb-item"><a href="#">Children</a></li>
    <li class="breadcrumb-item active">Relative</li>
  </ul>
  <h2>Progress</h2>
  <div class="progress">
    <div class="progress-bar progress-bar-striped progress-bar-animated" style="width:60%">60%</div>
  </div>
<h1>New Relative</h1>

<%= render 'form', relative: @relative %>

<%= link_to 'Back', relatives_path %>
</div>
<%= render "layouts/footer"%>

<style>
.container-background{
  height: 350px;
}
</style>

app/views/relatives/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Relative name:</strong>
  <%= @relative.relative_name %>
</p>

<p>
  <strong>Relative nric:</strong>
  <%= @relative.relative_nric %>
</p>

<p>
  <strong>Relative relationship:</strong>
  <%= @relative.relative_relationship %>
</p>

<p>
  <strong>Relative tel no:</strong>
  <%= @relative.relative_tel_no %>
</p>

<p>
  <strong>Relative hp no:</strong>
  <%= @relative.relative_hp_no %>
</p>

<p>
  <strong>Relative perm address:</strong>
  <%= @relative.relative_perm_address %>
</p>

<p>
  <strong>Relative postcode:</strong>
  <%= @relative.relative_postcode %>
</p>

<p>
  <strong>Personal detail:</strong>
  <%= @relative.personal_detail %>
</p>

<%= link_to 'Edit', edit_relative_path(@relative) %> |
<%= link_to 'Back', relatives_path %>