config/routes.rb
Rails.application.routes.draw do
  resources :beneficiaries
  resources :training_attendeds
  resources :honors_and_awards
  resources :professional_memberships
  resources :working_experiences
  resources :qualification_details
  resources :bank_accounts
  resources :payrolls
  resources :relatives
  resources :children
  resources :legal_spouses
  devise_for :users
  root 'pages#login'
  resources :personal_details
  resources :pins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'pins' => 'pins#index'
#personal_detail - spouse - children - relatives - qualification - experience - honor - training
  #registration routes
  get 'staff_register' => 'personal_details#new'
  get 'staff_register2' => 'legal_spouses#new'
  get 'staff_register3' => 'children#new'
  get 'staff_register4' => 'relatives#new'
  get 'staff_register5' => 'payrolls#new'
  get 'staff_register6' => 'bank_accounts#new'
  get 'staff_register7' => 'qualification_details#new'
  get 'staff_register8' => 'working_experiences#new'
  get 'staff_register9' => 'professional_memberships#new'
  get 'staff_register10' => 'honors_and_awards#new'
  get 'staff_register11' => 'training_attendeds#new'
  get 'staff_register_finish' => 'pages#finish_register_staff'

  get 'admin_home' => 'pages#admin_home'
  get 'view_all_staff' => 'pages#staff_management'
  get 'show_staff_table' => 'personal_details#index'
  get 'show_training_table' => 'training_attendeds#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bank_account.rb
class BankAccount < ApplicationRecord
  belongs_to :personal_detail
end

app/models/beneficiary.rb
class Beneficiary < ApplicationRecord
end

app/models/child.rb
class Child < ApplicationRecord
  belongs_to :personal_detail
end

app/models/honors_and_award.rb
class HonorsAndAward < ApplicationRecord
  belongs_to :personal_detail
end

app/models/legal_spouse.rb
class LegalSpouse < ApplicationRecord
  belongs_to :personal_detail
end

app/models/payroll.rb
class Payroll < ApplicationRecord
  belongs_to :personal_detail
end

app/models/personal_detail.rb
class PersonalDetail < ApplicationRecord

  has_one_attached :staff_image
  has_one :legal_spouse
end

app/models/pin.rb
class Pin < ApplicationRecord
end

app/models/professional_membership.rb
class ProfessionalMembership < ApplicationRecord
  belongs_to :personal_detail
end

app/models/relative.rb
class Relative < ApplicationRecord
  belongs_to :personal_detail
end

app/models/training_attended.rb
class TrainingAttended < ApplicationRecord
  belongs_to :personal_detail
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/working_experience.rb
class WorkingExperience < ApplicationRecord
  belongs_to :personal_detail
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = Pin.new
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = Pin.new(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:text1, :text2)
    end
end

app/controllers/professional_memberships_controller.rb
class ProfessionalMembershipsController < ApplicationController
  before_action :set_professional_membership, only: [:show, :edit, :update, :destroy]

  # GET /professional_memberships
  # GET /professional_memberships.json
  def index
    @professional_memberships = ProfessionalMembership.all
  end

  # GET /professional_memberships/1
  # GET /professional_memberships/1.json
  def show
  end

  # GET /professional_memberships/new
  def new
    @professional_membership = ProfessionalMembership.new
  end

  # GET /professional_memberships/1/edit
  def edit
  end

  # POST /professional_memberships
  # POST /professional_memberships.json
  def create
    @professional_membership = ProfessionalMembership.new(professional_membership_params)

    respond_to do |format|
      if @professional_membership.save
        format.html { redirect_to @professional_membership, notice: 'Professional membership was successfully created.' }
        format.json { render :show, status: :created, location: @professional_membership }
      else
        format.html { render :new }
        format.json { render json: @professional_membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /professional_memberships/1
  # PATCH/PUT /professional_memberships/1.json
  def update
    respond_to do |format|
      if @professional_membership.update(professional_membership_params)
        format.html { redirect_to @professional_membership, notice: 'Professional membership was successfully updated.' }
        format.json { render :show, status: :ok, location: @professional_membership }
      else
        format.html { render :edit }
        format.json { render json: @professional_membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /professional_memberships/1
  # DELETE /professional_memberships/1.json
  def destroy
    @professional_membership.destroy
    respond_to do |format|
      format.html { redirect_to professional_memberships_url, notice: 'Professional membership was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_professional_membership
      @professional_membership = ProfessionalMembership.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def professional_membership_params
      params.require(:professional_membership).permit(:association, :institution, :duration_date, :annual_subs, :personal_detail_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payrolls_helper.rb
module PayrollsHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/professional_memberships_helper.rb
module ProfessionalMembershipsHelper
end

app/helpers/relatives_helper.rb
module RelativesHelper
end

app/views/professional_memberships/_form.html.erb
<%= form_with(model: professional_membership, local: true) do |form| %>
  <% if professional_membership.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(professional_membership.errors.count, "error") %> prohibited this professional_membership from being saved:</h2>

      <ul>
      <% professional_membership.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :association %>
    <%= form.text_field :association %>
  </div>

  <div class="field">
    <%= form.label :institution %>
    <%= form.text_field :institution %>
  </div>

  <div class="field">
    <%= form.label :duration_date %>
    <%= form.text_field :duration_date %>
  </div>

  <div class="field">
    <%= form.label :annual_subs %>
    <%= form.text_field :annual_subs %>
  </div>

  <div class="field">
    <%= form.label :personal_detail_id %>
    <%= form.text_field :personal_detail_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/professional_memberships/edit.html.erb
<h1>Editing Professional Membership</h1>

<%= render 'form', professional_membership: @professional_membership %>

<%= link_to 'Show', @professional_membership %> |
<%= link_to 'Back', professional_memberships_path %>

app/views/professional_memberships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Professional Memberships</h1>

<table>
  <thead>
    <tr>
      <th>Association</th>
      <th>Institution</th>
      <th>Duration date</th>
      <th>Annual subs</th>
      <th>Personal detail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @professional_memberships.each do |professional_membership| %>
      <tr>
        <td><%= professional_membership.association %></td>
        <td><%= professional_membership.institution %></td>
        <td><%= professional_membership.duration_date %></td>
        <td><%= professional_membership.annual_subs %></td>
        <td><%= professional_membership.personal_detail %></td>
        <td><%= link_to 'Show', professional_membership %></td>
        <td><%= link_to 'Edit', edit_professional_membership_path(professional_membership) %></td>
        <td><%= link_to 'Destroy', professional_membership, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Professional Membership', new_professional_membership_path %>

app/views/professional_memberships/new.html.erb
<h1>New Professional Membership</h1>

<%= render 'form', professional_membership: @professional_membership %>

<%= link_to 'Back', professional_memberships_path %>

app/views/professional_memberships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Association:</strong>
  <%= @professional_membership.association %>
</p>

<p>
  <strong>Institution:</strong>
  <%= @professional_membership.institution %>
</p>

<p>
  <strong>Duration date:</strong>
  <%= @professional_membership.duration_date %>
</p>

<p>
  <strong>Annual subs:</strong>
  <%= @professional_membership.annual_subs %>
</p>

<p>
  <strong>Personal detail:</strong>
  <%= @professional_membership.personal_detail %>
</p>

<%= link_to 'Edit', edit_professional_membership_path(@professional_membership) %> |
<%= link_to 'Back', professional_memberships_path %>