config/routes.rb
Rails.application.routes.draw do
  resources :beneficiaries
  resources :training_attendeds
  resources :honors_and_awards
  resources :professional_memberships
  resources :working_experiences
  resources :qualification_details
  resources :bank_accounts
  resources :payrolls
  resources :relatives
  resources :children
  resources :legal_spouses
  devise_for :users
  root 'pages#login'
  resources :personal_details
  resources :pins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'pins' => 'pins#index'
#personal_detail - spouse - children - relatives - qualification - experience - honor - training
  #registration routes
  get 'staff_register' => 'personal_details#new'
  get 'staff_register2' => 'legal_spouses#new'
  get 'staff_register3' => 'children#new'
  get 'staff_register4' => 'relatives#new'
  get 'staff_register5' => 'payrolls#new'
  get 'staff_register6' => 'bank_accounts#new'
  get 'staff_register7' => 'qualification_details#new'
  get 'staff_register8' => 'working_experiences#new'
  get 'staff_register9' => 'professional_memberships#new'
  get 'staff_register10' => 'honors_and_awards#new'
  get 'staff_register11' => 'training_attendeds#new'
  get 'staff_register_finish' => 'pages#finish_register_staff'

  get 'admin_home' => 'pages#admin_home'
  get 'view_all_staff' => 'pages#staff_management'
  get 'show_staff_table' => 'personal_details#index'
  get 'show_training_table' => 'training_attendeds#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bank_account.rb
class BankAccount < ApplicationRecord
  belongs_to :personal_detail
end

app/models/beneficiary.rb
class Beneficiary < ApplicationRecord
end

app/models/child.rb
class Child < ApplicationRecord
  belongs_to :personal_detail
end

app/models/honors_and_award.rb
class HonorsAndAward < ApplicationRecord
  belongs_to :personal_detail
end

app/models/legal_spouse.rb
class LegalSpouse < ApplicationRecord
  belongs_to :personal_detail
end

app/models/payroll.rb
class Payroll < ApplicationRecord
  belongs_to :personal_detail
end

app/models/personal_detail.rb
class PersonalDetail < ApplicationRecord

  has_one_attached :staff_image
  has_one :legal_spouse
end

app/models/pin.rb
class Pin < ApplicationRecord
end

app/models/qualification_detail.rb
class QualificationDetail < ApplicationRecord
  belongs_to :personal_detail
end

app/models/relative.rb
class Relative < ApplicationRecord
  belongs_to :personal_detail
end

app/models/training_attended.rb
class TrainingAttended < ApplicationRecord
  belongs_to :personal_detail
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/working_experience.rb
class WorkingExperience < ApplicationRecord
  belongs_to :personal_detail
end

app/controllers/honors_and_awards_controller.rb
class HonorsAndAwardsController < ApplicationController
  before_action :set_honors_and_award, only: [:show, :edit, :update, :destroy]

  # GET /honors_and_awards
  # GET /honors_and_awards.json
  def index
    @honors_and_awards = HonorsAndAward.all
  end

  # GET /honors_and_awards/1
  # GET /honors_and_awards/1.json
  def show
  end

  # GET /honors_and_awards/new
  def new
    @honors_and_award = HonorsAndAward.new
@current_user_register = session[:register_session]
    @honors_and_awards = HonorsAndAward.all
  end

  # GET /honors_and_awards/1/edit
  def edit
  end

  # POST /honors_and_awards
  # POST /honors_and_awards.json
  def create
    @honors_and_award = HonorsAndAward.new(honors_and_award_params)
@honors_and_awards = HonorsAndAward.all
    respond_to do |format|
      if @honors_and_award.save
        format.html { redirect_to @honors_and_award, notice: 'Honors and award was successfully created.' }
        format.json { render :show, status: :created, location: @honors_and_award }
      else
        format.html { render :new }
        format.json { render json: @honors_and_award.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /honors_and_awards/1
  # PATCH/PUT /honors_and_awards/1.json
  def update
    respond_to do |format|
      if @honors_and_award.update(honors_and_award_params)
        format.html { redirect_to @honors_and_award, notice: 'Honors and award was successfully updated.' }
        format.json { render :show, status: :ok, location: @honors_and_award }
      else
        format.html { render :edit }
        format.json { render json: @honors_and_award.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /honors_and_awards/1
  # DELETE /honors_and_awards/1.json
  def destroy
    @honors_and_award.destroy
    respond_to do |format|
      format.html { redirect_to honors_and_awards_url, notice: 'Honors and award was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_honors_and_award
      @honors_and_award = HonorsAndAward.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def honors_and_award_params
      params.require(:honors_and_award).permit(:honor_or_award, :grantor, :date_received, :personal_detail_id)
    end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = Pin.new
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = Pin.new(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:text1, :text2)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/helpers/honors_and_awards_helper.rb
module HonorsAndAwardsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payrolls_helper.rb
module PayrollsHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/relatives_helper.rb
module RelativesHelper
end

app/views/honors_and_awards/_form.html.erb
<%= form_with(model: honors_and_award, local: true) do |form| %>
  <% if honors_and_award.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(honors_and_award.errors.count, "error") %> prohibited this honors_and_award from being saved:</h2>

      <ul>
      <% honors_and_award.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :honor_or_award %>
    <%= form.text_field :honor_or_award %>
  </div>

  <div class="field">
    <%= form.label :grantor %>
    <%= form.text_field :grantor %>
  </div>

  <div class="field">
    <%= form.label :date_received %>
    <%= form.date_select :date_received %>
  </div>

  <div class="field">
    <%= form.label :personal_detail_id %>
    <%= form.text_field :personal_detail_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/honors_and_awards/edit.html.erb
<h1>Editing Honors And Award</h1>

<%= render 'form', honors_and_award: @honors_and_award %>

<%= link_to 'Show', @honors_and_award %> |
<%= link_to 'Back', honors_and_awards_path %>

app/views/honors_and_awards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Honors And Awards</h1>

<table>
  <thead>
    <tr>
      <th>Honor or award</th>
      <th>Grantor</th>
      <th>Date received</th>
      <th>Personal detail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @honors_and_awards.each do |honors_and_award| %>
      <tr>
        <td><%= honors_and_award.honor_or_award %></td>
        <td><%= honors_and_award.grantor %></td>
        <td><%= honors_and_award.date_received %></td>
        <td><%= honors_and_award.personal_detail %></td>
        <td><%= link_to 'Show', honors_and_award %></td>
        <td><%= link_to 'Edit', edit_honors_and_award_path(honors_and_award) %></td>
        <td><%= link_to 'Destroy', honors_and_award, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Honors And Award', new_honors_and_award_path %>

app/views/honors_and_awards/new.html.erb
<%= render "layouts/menubar"%>
<div class="container">
  <ul class="breadcrumb">
    <li class="breadcrumb-item"><a href="#">Personal Detail</a></li>
    <li class="breadcrumb-item active">Legal Spouse</li>
  </ul>
  <h2>Progress</h2>
  <div class="progress">
    <div class="progress-bar progress-bar-striped progress-bar-animated" style="width:60%">60%</div>
  </div>

<h1>New Honors And Award</h1>
<fieldset>
  <legend>Insert Honor and Award </legend>
<%= render 'form', honors_and_award: @honors_and_award %>
</fieldset>
<br/>
<br/>
<fieldset>
  <legend>Show Honor and Award </legend>
  <h1>Honors And Awards</h1>

  <table border="1">
    <thead>
      <tr>
        <th>Honor or award</th>
        <th>Grantor</th>
        <th>Date received</th>
        <th>Personal detail</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @honors_and_awards.each do |honors_and_award| %>
        <tr>
          <td><%= honors_and_award.honor_or_award %></td>
          <td><%= honors_and_award.grantor %></td>
          <td><%= honors_and_award.date_received %></td>
          <td><%= honors_and_award.personal_detail %></td>
          <td><%= link_to 'Show', honors_and_award %></td>
          <td><%= link_to 'Edit', edit_honors_and_award_path(honors_and_award) %></td>
          <td><%= link_to 'Destroy', honors_and_award, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  </fieldset>
<%= link_to 'Back', honors_and_awards_path %>
<%= link_to 'Next', staff_register11_path, class: "btn"%>
</div>
<%= render "layouts/footer"%>

<style>
.container-background{
  height: 350px;
}
</style>

app/views/honors_and_awards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Honor or award:</strong>
  <%= @honors_and_award.honor_or_award %>
</p>

<p>
  <strong>Grantor:</strong>
  <%= @honors_and_award.grantor %>
</p>

<p>
  <strong>Date received:</strong>
  <%= @honors_and_award.date_received %>
</p>

<p>
  <strong>Personal detail:</strong>
  <%= @honors_and_award.personal_detail %>
</p>

<%= link_to 'Edit', edit_honors_and_award_path(@honors_and_award) %> |
<%= link_to 'Back', honors_and_awards_path %>